language: ruby
addons:
  postgresql: "9.6"
  firefox: lastest
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xf geckodriver-v0.21.0-linux64.tar.gz -C bin
  - export PATH=$PATH:$PWD/bin
  - export MOZ_HEADLESS=1
before_script:
  - bundle exec rails db:setup
  - yarn install
script:
  - bundle exec rails test
  - bundle exec rails test:system
