language: ruby
addons:
  postgresql: "9.6"
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rails db:setup
  - yarn install
script:
  - bundle exec rails test
